language: python

install:
  - pip install -r requirements.txt
  - pip install pep8
  - pip install nose

python:
  - "2.7"

script:
  - nosetests
  - pep8 pynetbox

deploy:
  - provider: pypi
    distributions: sdist
    server: https://upload.pypi.org/legacy/
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      branch: master
      tags: false
